# Your Website Title
title: Melvin Ch'ng

# Your Website URL
url: 'http://andremenezes295.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: André Luiz A. de Menezes
tagline: Estudante de Direito
pic: profile.png
description: Estudante de Direito
description_tiny: 'Centro Universitário de Cachoeirinha'
email: andrelz.am295@gmail.com
website: melvinchng.github.io # do not add http://
linkedin: realmelvinchng
github: melvinchng
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
