# Your Website Title
title: André Luiz A. de Menezes

# Your Website URL
url: 'http://andremenezes295.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: André Luiz A. de Menezes
tagline: Estudante de Direito
pic: <img src="profile.png" alt="foto">
description: Estudante de Direito
description_tiny: 'Centro Universitário de Cachoeirinha'
email: andrelz.am295@gmail.com
website: andremenezes295.github.io
linkedin: andrelzam/
github: andremenezes295

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
